[agentspace-dev]
image=registry.opensuse.org/opensuse/distrobox:latest

# replace with your own path to the agentspace repository:
# volume="/var/andy/repos/agentspace/:/workspace:rw"

root=false
pull=true
start_now=true

# Only bootstrap dependencies, not the development environment.
additional_packages="curl ca-certificates git"