services:
  kernel:
    build:
      context: ../..
      dockerfile: kernels/kernel_host/Dockerfile
    env_file:
      - .env
    environment:
      - LOG_LEVEL=DEBUG
    volumes:
      - copilot-config:/root/.copilot

  setup:
    build:
      context: ../..
      dockerfile: kernels/kernel_host/Dockerfile
    env_file:
      - .env
    environment:
      - LOG_LEVEL=DEBUG
    volumes:
      - copilot-config:/root/.copilot
    entrypoint: copilot
    stdin_open: true
    tty: true

volumes:
  copilot-config:
